name: test

on:
  push:
    branches: [main, test-*, playwright-test]

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  test_linux:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium]
        os: [ubuntu-18.04]
        node-version: [16.x]
    runs-on: ${{ matrix.os }}
    # ref: https://playwright.dev/docs/ci#github-actions
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: '7'
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps ${{ matrix.browser }}
      - name: Run tests
        run: pnpm test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report
